### ISSUE TITLE
Тех. долг |  Компоненты авторизации

### ISSUE THREAD

**Issue by nikitakaralius** [OnlySpans/PolyLeads#71]
Надо изучить как делать нормально аутентификацию и авторизацию. Желательно, чтобы это стыковалось с mobx и MVVM.
Прежде чем писать что-то свое, поищи готовые библиотеки, приложи в задачу - вместе выберем, если что-то подойдет.

**Comment by milkylake** [comment]
В общем есть всякие сервисы по типу [firebase ](https://firebase.google.com/docs/auth) [supabase ](https://supabase.com/docs/guides/auth) авторизации. 
Есть библиотека [nextAuth](https://next-auth.js.org/), но там нужна реализация бека для него.
Есть еще авторизация на основе токенов JWT, но я так понимаю там серверную часть переделывать надо.
![image](https://github.com/OnlySpans/PolyLeads/assets/126706140/8fab3528-bae6-459f-abab-697b63f52a94)

Если серверную часть трогать не будем, оставим как есть, то можно просто логику с авторицией и ролью пользователя вынести в отдельный модуль. Какой нибудь класс AuthService создать со всеми запросами и полями.

**Comment by nikitakaralius** [comment]
Сторонние сервисы использовать не будем, как и добавлять JWT токены. Сейчас авторизация у нас работает на session cookies, чего нам с головой хватает. Что-то тяжелее - это уже полноценный модуль авторизации, что дорого для нас.

NextAuth не подойдет, потому что придется реализовывать OAuth у нас (хотя, может есть готовые решения в виде библиотек)

Я поговорил с ребятами в офисе, авторизацию они делали так же, как и мы до этого. Осталось просто придумать нормальную обертку для всего этого дела

**Comment by nikitakaralius** [comment]
Пока ставим на паузу. Будет время - вернемся
