### ISSUE TITLE
v0.2.0 | Исследование LLM

### ISSUE THREAD

**Issue by nikitakaralius** [OnlySpans/PolyLeads#78]
Необходимо исследовать разные LLM, сравнить их, выбрать подходяшую для нас

Обращаем внимание на следующие факторы:
1. Качество работы с русским текстом
2. Максимальное количество токенов
3. Качество суммаризации текста
4. Стоимость: расход памяти, CPU, GPU, тарифный план

### YandexGPT
Здесь надо завести платежный аккаунт и посмотреть, во сколько нам будет обходиться использование. Бюджет до 2к для демо

### Ollama
https://ollama.com/

Они предоставляют разные модели, обученные на разном объеме данных. Как минимум, надо попробовать самые популярные.

**Comment by Berkas721** [comment]
Для локального развертывания нам не хватит мощностей. 
Если выбирать из апи то хорошо подходит gemini, но оно западное. Из российских продуктов есть только яндекс, он в целом подходит если мы сможем сокращать документы до 5к слов. Подробнее про особенности разных апи и примеры их работы в документиках.
[Выбор LLM.docx](https://github.com/user-attachments/files/15839741/LLM.docx)
[Примеры работы ЛЛМ.docx](https://github.com/user-attachments/files/15839740/default.docx)

**Comment by nikitakaralius** [comment]
Выбираем YandexGPT:
1. Политех сотрудничает с Яндексом. Гипотетически, обработку получится сделать вообще бесплатной для нас.
2. Невысокая цена за обработку
3. Есть варианты моделей, направленные конкретно на пересказ текста
4. Российский продукт, не надо будет поднимать VPN и т.п.
5. Изначально направлено на обработку русского текста

@Berkas721, спасибо
