### ISSUE TITLE
v0.2.0 | Разворачивание DEV среды LLM

### ISSUE THREAD

**Issue by nikitakaralius** [OnlySpans/PolyLeads#79]
Делаем интеграцию с YandexGPT. Для этого надо создать OnlySpans аккаунт в личном кабинете. Кажется, понадобится еще и почта. Логин и пароль отправить в наш чат

**Comment by Berkas721** [comment]
Сделал OnlySpans аккаунт, всех в него пригласил. В нем создал платежный аккаунт и облако/папку/сервисный аккаунт poly-leads для использования в нашем проекте.
