### ISSUE TITLE
v0.2.0 | Верстка страницы чата

### ISSUE THREAD

**Issue by nikitakaralius** [OnlySpans/PolyLeads#83]
Необходимо сверстать отдельную страницу с чатом. Ничего нового не придумываем - берем интерфейс ChatGPT и переносим его к себе. Экран должен содержать:

- сообщения от пользователя
- сообщения от чат-бота
- MultilineTextInput для ввода промпта
- Популярные запросы по умолчанию (гипотетически, можем получать с сервера, но пока нужды нет)

<img width="1223" alt="Screenshot 2024-06-20 at 22 29 30" src="https://github.com/OnlySpans/PolyLeads/assets/73189234/2f75ca37-122f-4150-a084-739c30bc36aa">

**Comment by milkylake** [comment]
Мне кажется запросы по умолчанию легче с фронта сделать, по сути просто готовый текст запроса передавать и все:)

**Comment by nikitakaralius** [comment]
Они и будут на фронте сейчас как заготовки. Просто с продуктовой точки зрения было бы прикольно анализировать частые запросы пользователей и автоматически обновлять список популярных запросов
